In [10]:
import torch

In [ ]:
from sklearn.datasets import make_classification

import torch

In [12]:
# step 1: Create a synthetic classification dataset using sklearn
X,y = make_classification(
    n_samples=10,  # Number of samples
    n_features=2,   # Number of features
    n_informative=2, # Number of informative features
    n_redundant=0,   # Number of redundant features
    n_classes=2,     # Number of classes
    random_state=42  # For reproducibility
)

In [13]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [14]:
X.shape

(10, 2)

In [15]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [16]:
y.shape

(10,)

In [17]:
#convert the data to Pytorch tensors
X = torch.tensor(X,dtype=torch.float32)
y = torch.tensor(y,dtype = torch.long)

In [18]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [19]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [22]:
import torch

In [30]:
from torch.utils.data import Dataset, DataLoader


In [31]:
class CustomDataset(Dataset):
    def __init__(self,features,labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return self.features.shape[0]
    
    def __getitem__(self,index):
        return self.features[index],self.labels[index]


In [ ]:
dataset = CustomDataset(X,y)

In [33]:
len(dataset)

10

In [35]:
dataset[4]

(tensor([-1.9629, -0.9923]), tensor(0))

In [45]:
dataloader = DataLoader(dataset, batch_size=3, shuffle=True)

In [46]:
for batch_features, batch_labels in dataloader:
    print(batch_features)
    print(batch_labels)
    print("-"*50)

tensor([[ 1.0683, -0.9701],
        [ 1.8997,  0.8344],
        [-0.9382, -0.5430]])
tensor([1, 1, 1])
--------------------------------------------------
tensor([[-1.1402, -0.8388],
        [ 1.7273, -1.1858],
        [-0.5872, -1.9717]])
tensor([0, 1, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.7206, -0.9606],
        [-2.8954,  1.9769]])
tensor([0, 0, 0])
--------------------------------------------------
tensor([[1.7774, 1.5116]])
tensor([1])
--------------------------------------------------


collate_fn ==> that specifies how to combine a list of samples from a dataset into a single batch.
