The torch.nn module in pytorch is a core library that provides a wide array of classes and functions designed to help developers build NN .
It abstracts the complexity of creating and training neural networks by offering pre-built layers,loss functions,activation functions, and other utilities.

In [6]:
#create model class
import torch
import torch.nn as nn 

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [7]:
#create dataset
features = torch.rand(10,5)
#create a model
model = Model(features.shape[1])
#call model for forward pass
#model.forward(features)

model(features)

tensor([[0.5943],
        [0.5965],
        [0.5463],
        [0.5780],
        [0.5989],
        [0.5182],
        [0.5153],
        [0.5488],
        [0.5616],
        [0.5706]], grad_fn=<SigmoidBackward0>)

In [ ]:
features.shape[0] #No of rows

10

In [ ]:

features.shape[1] # no of columns/fetaures

5

In [ ]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.0161, -0.0341, -0.0678,  0.0895,  0.3632]], requires_grad=True)

In [ ]:
#show model bias
model.linear.bias

Parameter containing:
tensor([0.1007], requires_grad=True)

In [13]:
!pip install torchinfo

  Obtaining dependency information for torchinfo from https://files.pythonhosted.org/packages/72/25/973bd6128381951b23cdcd8a9870c6dcfc5606cb864df8eabd82e529f9c1/torchinfo-1.8.0-py3-none-any.whl.metadata



[notice] A new release of pip is available: 23.2.1 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [14]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

MultiLayer Neural Network

In [15]:
import torch.nn as nn

In [20]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out =self.linear1(features)
        out = self.relu(out)
        out = self.linear2(out)
        out = self.sigmoid(out)
        return out

In [21]:
x = torch.rand(10,5)

In [22]:
model = Model(x.shape[1])

In [23]:
model(x)

tensor([[0.5216],
        [0.5016],
        [0.5458],
        [0.5538],
        [0.5566],
        [0.5115],
        [0.5285],
        [0.5148],
        [0.5522],
        [0.5101]], grad_fn=<SigmoidBackward0>)

In [24]:
model.linear1.weight

Parameter containing:
tensor([[-0.2396, -0.4435,  0.2590,  0.1204, -0.2553],
        [ 0.2113,  0.0109, -0.1900,  0.4088, -0.2919],
        [ 0.0757,  0.1325,  0.1062,  0.3714, -0.1373]], requires_grad=True)

In [25]:
model.linear2.weight

Parameter containing:
tensor([[0.5284, 0.3687, 0.2066]], requires_grad=True)

In [26]:
model.linear1.bias

Parameter containing:
tensor([ 0.3115, -0.0982,  0.3849], requires_grad=True)

In [27]:
model.linear2.bias

Parameter containing:
tensor([-0.0690], requires_grad=True)

In [28]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Cumbersome to write everything so, use Sequential Containers

In [29]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
    def forward(self,features):
        out =self.network(features)
        return out

In [31]:
feature = torch.rand(10,5)
model = Model(feature.shape[1])
model(feature)

tensor([[0.4017],
        [0.4175],
        [0.3982],
        [0.3914],
        [0.3867],
        [0.3728],
        [0.3931],
        [0.3887],
        [0.4115],
        [0.4135]], grad_fn=<SigmoidBackward0>)

In [32]:
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00