Breast cancer detection 

In [6]:
import numpy as np
import pandas as pd

In [7]:
import torch

In [8]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [9]:
df = pd.read_csv("breast-cancer.csv")
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [10]:
df.shape

(569, 32)

In [11]:
df.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [12]:
df.drop(columns=['id'],inplace=True)
df.shape

(569, 31)

In [13]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [14]:
X_train.shape

(455, 30)

In [15]:
y_train.shape

(455,)

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

In [17]:
X_train

array([[ 0.61460395, -0.10732738,  0.70743112, ...,  0.92259227,
        -0.18771839,  1.27967557],
       [ 0.20293202,  1.07443431,  0.24114416, ...,  0.74176024,
         0.75536885,  0.30644962],
       [-0.20310058, -0.77249693, -0.20510064, ...,  0.88581288,
         1.10795683,  1.01358121],
       ...,
       [-0.03392033, -1.38737874, -0.0488536 , ..., -0.17619221,
        -1.23178957, -0.63224069],
       [-1.22071977, -0.89135884, -1.13399335, ...,  0.67586382,
         0.39079974,  2.38934565],
       [ 2.11466882,  0.72013439,  2.06538964, ...,  1.66431011,
        -1.40294878, -0.71037052]], shape=(455, 30))

Label Encoding --> to convert categorical into numerical columns

In [18]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.fit_transform(y_test)

In [19]:
y_train

array([1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,

Numpy arrays to pytorch tensors

In [20]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [21]:
X_train_tensor.shape

torch.Size([455, 30])

In [22]:
y_train_tensor.shape

torch.Size([455])

In [36]:
print(X_train_tensor.dtype)
print(y_train_tensor.dtype)


torch.float64
torch.int64


In [37]:
X_train_tensor = X_train_tensor.float()
y_train_tensor = y_train_tensor.float()

In [38]:
print(X_train_tensor.dtype)
print(y_train_tensor.dtype)


torch.float32
torch.float32


Defining the model

In [39]:
import torch

In [52]:
import torch.nn as nn
class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        
        self.linear = nn.Linear(num_features,1)
        self.sigmoid =nn.Sigmoid()

        
    def forward(self,features):
        out =self.linear(features)
        out =self.sigmoid(out)
        return out
    # def loss_function(self,y_pred,y):
    #     epsilon = 1e-7
    #     y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
    #     loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1 -y_pred)).mean()
    #     return loss

In [ ]:
# feature = torch.rand(10,5)
# model = MySimpleNN(feature.shape[1])
# model(feature)

tensor([[0.5095],
        [0.4978],
        [0.4864],
        [0.5190],
        [0.5322],
        [0.5140],
        [0.5141],
        [0.4984],
        [0.5026],
        [0.5070]], grad_fn=<SigmoidBackward0>)

In [ ]:
# class MySimpleNN():
#     def __init__(self,X):
#         self.weights = torch.rand(X.shape[1],1, dtype=torch.float64,requires_grad =True)
#         self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)

#     def forward(self,X):
#         z = torch.matmul(X,self.weights) +self.bias
#         y_pred = torch.sigmoid(z)
#         return y_pred

#     def loss_function(self,y_pred,y):
#         epsilon = 1e-7
#         y_pred = torch.clamp(y_pred,epsilon,1-epsilon)
#         loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1 -y_pred)).mean()
#         return loss

Important Parameters

In [53]:
learning_rate = 0.1
epochs = 25

Training Pipeline

In [54]:
#built in loss function
loss_function = nn.BCELoss()

In [55]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [36]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [59]:
#create model
model = MySimpleNN(X_train_tensor.shape[1])
#define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
for i in range(epochs):
    y_pred = model(X_train_tensor)

    #define loop
    #forward pass
    #loss calculate
    #view --> reshape in torch

    #forward pass
    loss = loss_function(y_pred,y_train_tensor.view(-1,1))
    
    #clear gradients
    optimizer.zero_grad()

    #backward pass
    loss.backward()
    #parameters update
    # with torch.no_grad():

    #     model.linear.weight -= learning_rate*model.linear.weight.grad
    #     model.linear.bias -= learning_rate*model.linear.bias.grad
    #     model.linear.weight.grad.zero_()
    #     model.linear.bias.grad.zero_()

    #parameters update
    optimizer.step()
    
    #zero gradients
        
    #print loss in each epoch
    print(f'Epoch :{i+1},Loss: {loss.item()}')


Epoch :1,Loss: 0.8218975067138672
Epoch :2,Loss: 0.602423906326294
Epoch :3,Loss: 0.48929038643836975
Epoch :4,Loss: 0.4230874478816986
Epoch :5,Loss: 0.3788488805294037
Epoch :6,Loss: 0.3466595709323883
Epoch :7,Loss: 0.32186755537986755
Epoch :8,Loss: 0.30198973417282104
Epoch :9,Loss: 0.2855711579322815
Epoch :10,Loss: 0.2716975212097168
Epoch :11,Loss: 0.2597625255584717
Epoch :12,Loss: 0.2493462860584259
Epoch :13,Loss: 0.24014785885810852
Epoch :14,Loss: 0.2319449782371521
Epoch :15,Loss: 0.22456945478916168
Epoch :16,Loss: 0.21789135038852692
Epoch :17,Loss: 0.21180817484855652
Epoch :18,Loss: 0.20623797178268433
Epoch :19,Loss: 0.20111419260501862
Epoch :20,Loss: 0.19638195633888245
Epoch :21,Loss: 0.1919955611228943
Epoch :22,Loss: 0.18791665136814117
Epoch :23,Loss: 0.18411245942115784
Epoch :24,Loss: 0.18055501580238342
Epoch :25,Loss: 0.17722013592720032


In [43]:
model.linear.weight

Parameter containing:
tensor([[ 2.6291e-02,  6.7575e-02,  1.0683e-01, -1.5121e-01,  8.8105e-02,
         -4.6112e-02,  7.5978e-03, -2.8978e-02,  3.2830e-02,  1.5374e-01,
          5.5318e-02, -3.6547e-02, -5.2829e-03,  2.2912e-02,  3.3000e-02,
          1.4926e-01,  3.0302e-02, -5.2666e-02, -1.5687e-01, -7.6645e-02,
         -6.7075e-05, -5.6827e-02,  3.3459e-02, -9.6811e-03, -5.3481e-02,
         -6.2448e-02, -1.9489e-02,  1.9390e-02, -3.7259e-03, -1.2801e-01]],
       requires_grad=True)

In [44]:
model.linear.bias

Parameter containing:
tensor([-0.3304], requires_grad=True)

Evaluation

In [47]:
X_test_tensor = X_test_tensor.float()
y_test_tensor = y_test_tensor.float()

In [60]:
#model Evaluation
with torch.no_grad():
    y_pred = model(X_test_tensor)
    y_pred =(y_pred >0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")
    

Accuracy: 0.5344721674919128


In [49]:
y_pred

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

torch.optim is a module in pytorch provides a variety of optimisation algorithms used to update the parameters of your model during traing

It includes SGD,Adam,RMSprop..
It takes two parameters model.parameters(),learning_rate
model.parameters() -->iterate over all the trainable parameters(weights and biases)