In [1]:
import torch
print(torch.__version__)

2.7.0+cpu


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using Gpu: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPu.")

GPU not available. Using CPu.


In [4]:
### Creating a Tensors

In [9]:
## using empty ---> create empty tensor with already exixting values stored in memory
torch.empty(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
a = torch.empty(2,3)

In [11]:
#check type
type(a)

torch.Tensor

In [12]:
#using zeros --> initialise tensor to zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [13]:
##using ones -->Initialise tensor to ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand --> within 0-1 range randomly
torch.rand(2,3)

tensor([[0.9749, 0.4530, 0.4431],
        [0.1226, 0.9343, 0.7612]])

In [15]:
torch.rand(2,3)

tensor([[0.9076, 0.4557, 0.9398],
        [0.3266, 0.0404, 0.7967]])

In [16]:
#using seed --> to generate same random numbers when we execute
#manual_seed
torch.manual_seed(140)
torch.rand(2,3)

tensor([[0.4638, 0.7986, 0.8355],
        [0.9407, 0.2521, 0.9259]])

In [17]:
torch.manual_seed(140)
torch.rand(2,3)

tensor([[0.4638, 0.7986, 0.8355],
        [0.9407, 0.2521, 0.9259]])

In [18]:
#using tensor --> to made custom tensors
torch.tensor([
    [1,2,3],
    [4,5,6]
])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [21]:
#arange --> 1d tensor within range specifing the jump
print("Using arange ->",torch.arange(0,10,3))

Using arange -> tensor([0, 3, 6, 9])


In [22]:
#using linspace --> within range linearly spaced elements with no.of elements we need
print("Using linspace ->",torch.linspace(0,10,15))

Using linspace -> tensor([ 0.0000,  0.7143,  1.4286,  2.1429,  2.8571,  3.5714,  4.2857,  5.0000,
         5.7143,  6.4286,  7.1429,  7.8571,  8.5714,  9.2857, 10.0000])


In [26]:
#using eye --> to create identity tensor
print(torch.eye(5))
print(torch.eye(3,3))

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


In [28]:
#using full --> to fill same element to the tensor with parameters of matrix dimensions and value
print(torch.full((3,3),5))

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [29]:
# Tensor Shape

In [30]:
x = torch.tensor([[1,2,4],[5,6,7]])
x

tensor([[1, 2, 4],
        [5, 6, 7]])

In [31]:
x.shape

torch.Size([2, 3])

In [33]:
#generating tensor with same shape of x
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [34]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [35]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x)
## issue arises because of rand generates a floating point values whereas x is integers

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [ ]:
##Tensor Data Types

In [37]:
x

tensor([[1, 2, 4],
        [5, 6, 7]])

In [ ]:
#find the data types
x.dtype

torch.int64

In [39]:
#assign data types
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [40]:
torch.tensor([1,2,3],dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [41]:
#using to() --> to convert into another datatype
x

tensor([[1, 2, 4],
        [5, 6, 7]])

In [42]:
x.to(torch.float32)

tensor([[1., 2., 4.],
        [5., 6., 7.]])

In [47]:
x=torch.tensor([[2,3,4],[5,6,7]])

In [48]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.2120, 0.2648, 0.6167],
        [0.7709, 0.3080, 0.5728]], dtype=torch.float64)

In [ ]:
#Mathematical Operations

In [49]:
x= torch.rand(2,3)
x

tensor([[0.0702, 0.6158, 0.2246],
        [0.5839, 0.3243, 0.1169]])

In [61]:
#1.Scalar Operation
#addition
x+5
#subtraction
x-3
#multiplication
x *3
#division
x/3
# int division
(x*100)//3
#mod
((x*100)//3)%2
#power
x**3

tensor([[0.0003, 0.2335, 0.0113],
        [0.1991, 0.0341, 0.0016]])

2.element wise operations

In [63]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2476, 0.2486, 0.6064],
        [0.3956, 0.3552, 0.4059]])
tensor([[0.9706, 0.6362, 0.5688],
        [0.4151, 0.7162, 0.5920]])


In [64]:
#addition
a + b

tensor([[1.2182, 0.8847, 1.1752],
        [0.8108, 1.0714, 0.9978]])

In [65]:
#subtraction
a - b

tensor([[-0.7230, -0.3876,  0.0376],
        [-0.0195, -0.3610, -0.1861]])

In [66]:
#multiply
a * b

tensor([[0.2404, 0.1581, 0.3449],
        [0.1642, 0.2544, 0.2403]])

In [67]:
#division
a / b 

tensor([[0.2551, 0.3907, 1.0660],
        [0.9530, 0.4960, 0.6856]])

In [69]:
#power
print(a ** b)
# mod
print(a % b)

tensor([[0.2580, 0.4125, 0.7523],
        [0.6805, 0.4765, 0.5864]])
tensor([[0.2476, 0.2486, 0.0376],
        [0.3956, 0.3552, 0.4059]])


In [74]:
c = torch.tensor([-1,2,3,4]
)

In [ ]:
#absolute
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
#Negation
torch.neg(c)

tensor([ 1, -2, -3, -4])

In [77]:
d = torch.tensor([1.9,2.3,3.7,4.4])

In [78]:
#round
torch.round(d)

tensor([2., 2., 4., 4.])

In [79]:
#ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [80]:
#floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [82]:
#clamp --> min,max lower than min returns min ,greater than max returns max
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction operation --> from tensor to single value 

In [89]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[8., 3., 6.],
        [4., 9., 8.]])

In [90]:
#sum
torch.sum(e)

tensor(38.)

In [91]:
#sum along columns
torch.sum(e,dim=0)

tensor([12., 12., 14.])

In [92]:
#sum along rows
torch.sum(e,dim=1)

tensor([17., 21.])

In [93]:
#mean 
torch.mean(e)

tensor(6.3333)

In [94]:
#mean along columns
print(torch.mean(e,dim=0))
#mean along rows
print(torch.mean(e,dim=1))

tensor([6., 6., 7.])
tensor([5.6667, 7.0000])


In [95]:
torch.median(e)

tensor(6.)

In [96]:
torch.max(e)


tensor(9.)

In [97]:
torch.min(e)

tensor(3.)

In [98]:
#product
torch.prod(e)

tensor(41472.)

In [99]:
#standard deviation
torch.std(e)

tensor(2.4221)

In [100]:
torch.var(e)

tensor(5.8667)

In [ ]:
#argmax --> position of maximum element in tensor starting counting with 0 in number in rows
torch.argmax(e) 

tensor(4)

In [102]:
#argmin
torch.argmin(e)

tensor(1)

Matrix Operations

In [103]:
f = torch.randint(size=(2,3),low =0,high=10)
g = torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[6, 6, 8],
        [6, 2, 7]])
tensor([[6, 1],
        [1, 8],
        [9, 2]])


In [104]:
#matrix multiplication
torch.matmul(f,g)

tensor([[114,  70],
        [101,  36]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])
#dot product -->(1*3)+(2*4) =11
torch.dot(vector1,vector2)

tensor(11)

In [106]:
#transpose
f

tensor([[6, 6, 8],
        [6, 2, 7]])

In [107]:
torch.transpose(f,0,1)

tensor([[6, 6],
        [6, 2],
        [8, 7]])

In [108]:
torch.transpose(f,1,0)

tensor([[6, 6],
        [6, 2],
        [8, 7]])

In [110]:
h = torch.randint(size=(3,3),low =0,high=10,dtype=torch.float32)
h

tensor([[5., 4., 7.],
        [9., 0., 2.],
        [9., 8., 8.]])

In [111]:
#determinant
torch.det(h)

tensor(208.0000)

In [112]:
#inverse 
torch.inverse(h)

tensor([[-0.0769,  0.1154,  0.0385],
        [-0.2596, -0.1106,  0.2548],
        [ 0.3462, -0.0192, -0.1731]])

Comparison Operations

In [113]:
i = torch.randint(size=(2,3),low=0,high=10)
j = torch.randint(size=(2,3),low =0,high =10)
print(i)
print(j)

tensor([[8, 6, 8],
        [0, 9, 7]])
tensor([[3, 1, 0],
        [6, 0, 0]])


In [114]:
#greater than
i >j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [115]:
#less than
i < j

tensor([[False, False, False],
        [ True, False, False]])

In [116]:
#equal to
i == j

tensor([[False, False, False],
        [False, False, False]])

In [117]:
# not equal to
i != j

tensor([[True, True, True],
        [True, True, True]])

In [118]:
#greater than equal to
i >= j

tensor([[ True,  True,  True],
        [False,  True,  True]])

In [119]:
# less than equal to
i <= j

tensor([[False, False, False],
        [ True, False, False]])

Special Functions

In [127]:
k = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[0., 9., 1.],
        [3., 8., 4.]])

In [128]:
#log
torch.log(k)

tensor([[  -inf, 2.1972, 0.0000],
        [1.0986, 2.0794, 1.3863]])

In [129]:
#exp
torch.exp(k)

tensor([[1.0000e+00, 8.1031e+03, 2.7183e+00],
        [2.0086e+01, 2.9810e+03, 5.4598e+01]])

In [130]:
#sqrt
torch.sqrt(k)

tensor([[0.0000, 3.0000, 1.0000],
        [1.7321, 2.8284, 2.0000]])

In [131]:
#sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9999, 0.7311],
        [0.9526, 0.9997, 0.9820]])

In [132]:
#softmax
torch.softmax(k,dim=0)

tensor([[0.0474, 0.7311, 0.0474],
        [0.9526, 0.2689, 0.9526]])

In [133]:
#relu
torch.relu(k)

tensor([[0., 9., 1.],
        [3., 8., 4.]])

Inplace Operations --> _ represents inplace operation e.g: add_,relu_

In [135]:
m= torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.4127, 0.7801, 0.5304],
        [0.2789, 0.0154, 0.9150]])
tensor([[0.7898, 0.6922, 0.2935],
        [0.7312, 0.7862, 0.3973]])


In [136]:
m.add_(n)

tensor([[1.2025, 1.4723, 0.8239],
        [1.0102, 0.8016, 1.3123]])

In [137]:
m

tensor([[1.2025, 1.4723, 0.8239],
        [1.0102, 0.8016, 1.3123]])

In [138]:
torch.relu(m)

tensor([[1.2025, 1.4723, 0.8239],
        [1.0102, 0.8016, 1.3123]])

In [140]:
m

tensor([[1.2025, 1.4723, 0.8239],
        [1.0102, 0.8016, 1.3123]])

In [141]:
m.relu_()

tensor([[1.2025, 1.4723, 0.8239],
        [1.0102, 0.8016, 1.3123]])

In [142]:
m

tensor([[1.2025, 1.4723, 0.8239],
        [1.0102, 0.8016, 1.3123]])

Copying a Tensor

In [180]:
a = torch.rand(2,3)
a

tensor([[0.1826, 0.9005, 0.9307],
        [0.6405, 0.5600, 0.7492]])

In [145]:
b = a
b

tensor([[0.6297, 0.2172, 0.4500],
        [0.2022, 0.6223, 0.1473]])

In [146]:
# by above if a changes b automatically changes with respect to a
a[0][0]=0
a

tensor([[0.0000, 0.2172, 0.4500],
        [0.2022, 0.6223, 0.1473]])

In [147]:
b

tensor([[0.0000, 0.2172, 0.4500],
        [0.2022, 0.6223, 0.1473]])

In [148]:
#copy (doesnot chang the copied version)
id(a)

1453243937360

In [149]:
id(b)

1453243937360

In [150]:
#using clone
b = a.clone()

In [151]:
b

tensor([[0.0000, 0.2172, 0.4500],
        [0.2022, 0.6223, 0.1473]])

In [152]:
a[0][0] =1
a

tensor([[1.0000, 0.2172, 0.4500],
        [0.2022, 0.6223, 0.1473]])

In [153]:
b

tensor([[0.0000, 0.2172, 0.4500],
        [0.2022, 0.6223, 0.1473]])

In [154]:
id(a)

1453243937360

In [155]:
id(b)

1453243956864

Reshaping Tensors

In [156]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
#reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [158]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [160]:
b = torch.rand(2,3,4)
b

tensor([[[0.7164, 0.5751, 0.2495, 0.0320],
         [0.0243, 0.9553, 0.5688, 0.6120],
         [0.6900, 0.4161, 0.3959, 0.6941]],

        [[0.1078, 0.0892, 0.5717, 0.0500],
         [0.0225, 0.8839, 0.9934, 0.4231],
         [0.8002, 0.1638, 0.1978, 0.1571]]])

In [161]:
#permute
b.permute(2,0,1).shape


torch.Size([4, 2, 3])

In [162]:
#unsqueeze --> adding dimension at specified index
#image size
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [163]:
c.unsqueeze(2).shape

torch.Size([226, 226, 1, 3])

In [165]:
#squeeze
d = torch.rand(1,20)
d

tensor([[4.7847e-01, 3.8793e-01, 7.2929e-01, 6.1849e-01, 9.3888e-01, 4.3523e-04,
         5.7201e-01, 1.7071e-01, 8.2205e-01, 3.1894e-02, 6.8774e-01, 9.7158e-01,
         1.3054e-01, 1.7591e-01, 3.1715e-01, 7.2886e-01, 5.5545e-01, 3.3492e-01,
         8.2511e-01, 7.4068e-01]])

In [166]:
d.squeeze(0).shape

torch.Size([20])

Numpy and Pytorch

In [167]:
import numpy as np


In [168]:
a =torch.tensor([1,2,4])
a

tensor([1, 2, 4])

from tensor to numpy

In [170]:
b = a.numpy()
b

array([1, 2, 4])

In [171]:
type(b)

numpy.ndarray

from numpy array to tensor

In [172]:
c =np.array([1,2,5])
c

array([1, 2, 5])

In [176]:
d= torch.from_numpy(c)
d

tensor([1, 2, 5])

In [177]:
type(d)

torch.Tensor